# Generated by Django 2.2.5 on 2022-09-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_auto_20220929_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='nilai',
            field=models.FloatField(default=90.0),
        ),
    ]
